version: '3.4'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql57
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - /home/user/db/mysql/data:/var/lib7mysql
      - /home/user/db/mysql/init:/docker-entrypoint-initdb.d/:ro
    environment:
      - MYSQL_DATABASE=DOCKERWEB
      - MYSQL_HOST=localhost
      - MYSQL_ROOT_PASSWORD=secret_password
  
  nodejs:
    image: f0e15b9b06d1
    ports:
      - "1080:3000"
    container_name: node-dockerweb 
    restart: always
    build: 
      context: .
    depends_on:
      - mysql
    environment:
      - MYSQL_DATABASE=DOCKERWEB
      - MYSQL_HOST=localhost
      - MYSQL_ROOT_PASSWORD=secret_password 

  